on:
  push:
    branches:
      - master
name: Deploy to prod environment
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: docker://anxing131/wetodos-cicd-base-img
        with:
          args: npm install
      - name: cp dynamodb
        uses: docker://anxing131/wetodos-cicd-base-img
        with:
          args: cp -R /WeTodos-serverless/.dynamodb .
      - name: mkdir tmp dir
        uses: docker://anxing131/wetodos-cicd-base-img
        with:
          args: java -version
      - name: java env
        uses: docker://anxing131/wetodos-cicd-base-img
        with:
          args: env
      - name: testing
        uses: docker://anxing131/wetodos-cicd-base-img
        with:
          args: JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64  JRE_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre CLASSPATH=.:/usr/lib/jvm/java-8-openjdk-amd64/lib:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib npm run start
#      - name: install dynamodb
#        run: sls dynamodb install
#      - name: testing
#        run: npm run test
