on:
  push:
    branches:
      - master
name: Deploy to prod environment
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        run: |
          curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
          sudo apt install -y nodejs
          node -v
          npm -version
          sudo npm i -g serverless
          sudo npm i
          echo $PWD
          export PWD=$(pwd)
          echo $PWD
          sudo sls dynamodb install
          sudo npm run test
      - name: npm version
        run: |
          npm -version
          node -v
          echo $PWD
          export PWD=$(pwd)
          echo $PWD
