on:
  push:
    branches:
      - master
name: Deploy to prod environment
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: docker://anxing131/wetodos-cicd-base-img
        with:
          args: npm install && mkdir -p tmp
      - name: install dynamodb
        uses: docker://anxing131/wetodos-cicd-base-img
        with:
          args: sls dynamodb install
      - name: testing
        uses: docker://anxing131/wetodos-cicd-base-img
        with:
          args: npm run test
#      - name: install dynamodb
#        run: sls dynamodb install
#      - name: testing
#        run: npm run test
