on:
  push:
    branches:
      - master
name: Deploy to prod environment
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: install serverless
        run: sudo npm i -g serverless
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/npm@master
        with:
          args: install
      - name: echo
        run: ls && pwd && echo $HOME && echo $GITHUB_WORKSPACE
      - name: install dynamodb
        run: export CNAME=$GITHUB_WORKSPACE && sudo sls dynamodb install
      - name: testing
        # uses: actions/npm@master
        run: npm run test
        # with:
        #   args: run test
        # env:
          # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          # or if using AWS creds directly
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
