on:
  push:
    branches:
      - master
name: Deploy to prod environment
jobs:
  deploy:
    name: deploy
    runs-on: anxing131/wetodos-cicd-base-img
    steps:
      - uses: actions/checkout@master
      - name: npm install
        run: npm install
      - name: install dynamodb
        run: sls dynamodb install
      - name: testing
        run: npm run test
