on:
  push:
    branches:
      - master
name: Deploy to prod environment
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: anxing131/wetodos-cicd-base-img
        with:
          entrypoint: /bin/bash
          args: npm install
#      - name: install dynamodb
#        run: sls dynamodb install
#      - name: testing
#        run: npm run test
