on:
  push:
    branches:
      - master
name: Deploy to prod environment
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: anxing131/wetodos-cicd-base-img
        with:
          args: npm install

      - name: install dynamodb
        uses: anxing131/wetodos-cicd-base-img
        with:
          args: sls dynamodb install
      - name: testing
        uses: anxing131/wetodos-cicd-base-img
        run: npm run test
        # with:
        #   args: run test
        # env:
          # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          # or if using AWS creds directly
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
